### ISSUE TITLE
Issue with Ignore

### ISSUE THREAD

**Issue by RyanReedUSE** [yamadashy/repomix#1]
Hello, 

This seems like a really great start to the package, so nice work! Any suggestions on how to ignore all SVG, CSS, etc. files? That does not appear to be working as I would expect. 

![image](https://github.com/user-attachments/assets/a4fbacdc-0f9a-4e45-a952-17366a6d4473)
![image](https://github.com/user-attachments/assets/df29e427-4837-4c17-9380-4e322d276a84)

Thanks,

**Comment by yamadashy** [comment]
Thank you for trying out Repopack and for your feedback! I'm sorry you encountered some issues with the ignore patterns. You're right, it should work with patterns like `*.svg` in the custom patterns.

I'll take a closer look at the ignore functionality tomorrow to see if there are any bugs or inconsistencies. If you notice any other issues or have additional feedback, please don't hesitate to let me know. Your input is really valuable for improving Repopack.

Thanks again for your patience and for using the package!

**Comment by yamadashy** [comment]
I've investigated and added more tests (https://github.com/yamadashy/repopack/pull/3), but couldn't reproduce the issue.

If you encounter it again, please share.

Your feedback is valuable for improving Repopack. Thank you!
