### ISSUE TITLE
Support comments in `repomix.config.json`

### ISSUE THREAD

**Issue by rockmandash** [yamadashy/repomix#209]
When dealing with a large codebase, people need to rapidly select which file paths to ignore and which to **include** in order to achieve acceptable token counts. The ability to add comments to `repomix.config.json` is critical.

**Comment by yamadashy** [comment]
Hi, @rockmandash !
Thank you for the suggestion.

While JSON comments can be controversial, many config files like eslintrc.json and tsconfig.json support them. @ivanionut have already enabled comment support through PR #214 which configures Biome to allow comments in JSON files.

- https://github.com/yamadashy/repomix/pull/214

This change will be included in the next release.

**Comment by yamadashy** [comment]
Thanks to @ivanionut 's contribution, this has been released in v0.2.7!

https://github.com/yamadashy/repomix/releases/tag/v0.2.7

Please try it out!
