### ISSUE TITLE
Ignored files can't be found in folder tree.

### ISSUE THREAD

**Issue by rockmandash** [yamadashy/repomix#210]
Add an option to keep it.

**Comment by yamadashy** [comment]
@rockmandash
Thank you for your suggestion!

It seems similar to #181, but the requirement is indeed different.

I understand there's a need to show ignored files in the file structure. However, simply showing all of them would raise issues like how to handle `node_modules`, and ignoring only a part of them doesn't seem like a clean solution either.

I think the approach in #181 might be a better way to go, but I'm not entirely convinced yet. I'd like to think about it a little more.
