### ISSUE TITLE
Add support for Docker

### ISSUE THREAD

**Issue by gaby** [yamadashy/repomix#221]
Add support for running `repomix` using Docker.

**Comment by yamadashy** [comment]
@gaby 
Thank you for implementing Docker support!

While there are no code changes, I've released v0.2.10 and written release notes to document your contribution:
https://github.com/yamadashy/repomix/releases/tag/v0.2.10

This is particularly exciting as it makes Repomix accessible to Python users and others who prefer not to manage Node.js installations.

Looking forward to your future contributions!

**Comment by gaby** [comment]
@yamadashy I noticed you changed the rules in the workflow. That will cause the `main` tag not to be published. Unless you don't want that one which is fine.

This part handles tagging when you do a GitHub release which is diff than creating a tag via `git`.

```yaml
  release:
    types: [published, edited]
```

**Comment by yamadashy** [comment]
@gaby 
You're right, sorry for the confusion!
Going back to using main branch triggers. I had changed it to tags without thinking it through carefully. Thanks for catching this.

https://github.com/yamadashy/repomix/pull/233

**Comment by yamadashy** [comment]
I've reverted the change back, so the `main` tag and github release will now be published correctly on GitHub releases!

https://github.com/yamadashy/repomix/pkgs/container/repomix

Thank you again for your valuable feedback!

**Comment by gaby** [comment]
@yamadashy Thank you, this can be closed now. :-) I will try doing other PR's in the future!
