### ISSUE TITLE
Feature request: global configuration equivalent of repopack.config.json

### ISSUE THREAD

**Issue by silembir** [yamadashy/repomix#51]
Hi,

I have been using repopack and really like the configurability. However, I typically use the same repopack config settings for most projects and it would be nice if I could have a global `repopack.config.json` in `~/.config/` or something that would take effect if a local config file is not present.  It didn't seem like this was already possible, or at least I did not see anything to that effect. Any help would be appreciated. Thank you!

**Comment by yamadashy** [comment]
Hi, @silembir 

Great idea! I've been copying and pasting the repopack config myself recently when trying to understand several libraries. 

You're right, having a global config would eliminate this hassle and allow for quick execution with preferred settings.

At the moment, my vision is as follows:
Repopack will look for a local `repopack.config.json` in the project root. If not found, it will use a global config located at `~/.config/repopack/repopack.config.json` (Unix) or `%USERPROFILE%\.config\repopack\repopack.config.json` (Windows). The local config, if present, will always take precedence over the global one.

What do you think?

Thank you for this valuable suggestion!

**Comment by yamadashy** [comment]
Hi,

I'm excited to share that I've implemented the global configuration feature based on your suggestion. You can find the details in the following Pull Request:

* https://github.com/yamadashy/repopack/pull/52

Regarding the file paths, I've taken inspiration from various tools and decided on the following structure:

- Windows: `%LOCALAPPDATA%\Repopack\repopack.config.json`
- macOS/Linux: `$XDG_CONFIG_HOME/repopack/repopack.config.json` or `~/.config/repopack/repopack.config.json`

The local config, if present, will always take precedence over the global one.

What do you think about this implementation? Does it align with what you had in mind?

Thank you again for this valuable suggestion.

**Comment by yamadashy** [comment]
I'll proceed with testing and merging this implementation.

If you have any further feedback, please don't hesitate to let me know.
Thank you again for this valuable suggestion!
