### ISSUE TITLE
Turn off security check?

### ISSUE THREAD

**Issue by ylluminate** [yamadashy/repomix#74]
It would be helpful to turn off security checks when we're working with developing cryptographic libraries... Can we have an argument flag to simply turn this function off when needed?

**Comment by yamadashy** [comment]
Hi,
Thank you for this valuable feedback!

I'll work on implementing this feature as soon as I get home.

**Comment by yamadashy** [comment]
Hi @ylluminate,

I've implemented the feature you requested in my latest release!
https://github.com/yamadashy/repopack/releases/tag/v0.1.36

You can now control the security check with the new `security.enableSecurityCheck` option in your `repopack.config.json` file. Here's how you can use it:

```json
{
  "security": {
    "enableSecurityCheck": false
  }
}
```

This will allow you to disable the security check when needed.

I'd love to hear your feedback on this implementation. Please give it a try and let us know how it works for your use case.

Thank you for your valuable input that led to this feature!

**Comment by yamadashy** [comment]
Awesome! I'm so glad to hear it's working well for you. Thanks for your feedback and for helping make Repopack better! 😊
